In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('C:\\Users\\Acer\\OneDrive\\Desktop\\Data Science\\netflix_titles.csv')

## 1. How big is the data ?

In [8]:
df.shape

(8807, 12)

## 2.How data looklike?

In [ ]:
df.sample(5) ## It provide random data from dataset.

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7318,s7319,Movie,Little Singham Bandarpur Mein Hu Ha Hu,NaN,"Anamaya Verma, Ganesh Divekar, Jigna Bharadhwa...",NaN,"July 11, 2019",2019,TV-Y7,67 min,"Children & Family Movies, Comedies","Little Singham's sidekick monkey, Chikki, is s..."
997,s998,TV Show,Life in Color with David Attenborough,NaN,David Attenborough,"Australia, United Kingdom","April 22, 2021",2021,TV-PG,1 Season,"British TV Shows, Docuseries, International TV...","Using innovative technology, this docuseries e..."
4586,s4587,Movie,Mugamoodi,Mysskin,"Jiiva, Pooja Hegde, Narain, Nasser, Girish Kar...",India,"October 1, 2018",2012,TV-14,150 min,"Action & Adventure, International Movies",A martial arts specialist accidentally becomes...
2053,s2054,TV Show,Young Wallander,NaN,"Adam Pålsson, Richard Dillane, Leanne Best, El...",United Kingdom,"September 3, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","An incendiary hate crime stirs civil unrest, f..."
7917,s7918,Movie,Sadma,Balu Mahendra,"Kamal Hassan, Sridevi, Silk Smitha, Gulshan Gr...",India,"December 31, 2019",1983,TV-14,137 min,"Dramas, International Movies, Romantic Movies",After a traumatic injury leaves her with amnes...

## 3. what is the datatype of cols?

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

## 4. Are there missing value ?

In [13]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

## Mathematical Values

In [16]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

## Are Duplicates ?

In [17]:
df.duplicated().sum()

np.int64(0)

## How is correlation between cols?

In [ ]:
df.corr() ## This will show the correlation between different numerical features in the dataset.