In [51]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator, SimpleImputer

In [52]:
df = pd.read_csv(r'c:\Users\Acer\OneDrive\Desktop\Machine Learning\CSV\tested.csv',usecols=['Age','Fare','Survived'])

In [53]:
df.head()

   Survived   Age     Fare
0         0  34.5   7.8292
1         1  47.0   7.0000
2         0  62.0   9.6875
3         0  27.0   8.6625
4         1  22.0  12.2875

In [54]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [55]:
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [56]:
X_train.head()

      Age     Fare
280  23.0   8.6625
284   2.0  20.2125
40   39.0  13.4167
17   21.0   7.2250
362  31.0  21.0000

In [57]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [58]:
X_train_trf

array([[2.30000000e+01, 8.66250000e+00],
       [2.00000000e+00, 2.02125000e+01],
       [3.90000000e+01, 1.34167000e+01],
       [2.10000000e+01, 7.22500000e+00],
       [3.10000000e+01, 2.10000000e+01],
       [8.00000000e+00, 2.60000000e+01],
       [2.93072519e+01, 7.00000000e+00],
       [3.70000000e+01, 8.31583000e+01],
       [1.70000000e+01, 4.71000000e+01],
       [3.10000000e+01, 2.10000000e+01],
       [8.30000000e-01, 9.35000000e+00],
       [2.93072519e+01, 2.65500000e+01],
       [2.20000000e+01, 8.96250000e+00],
       [2.93072519e+01, 2.16792000e+01],
       [2.70000000e+01, 7.89580000e+00],
       [2.10000000e+01, 7.85420000e+00],
       [4.50000000e+01, 6.33583000e+01],
       [2.20000000e+01, 1.05000000e+01],
       [2.93072519e+01, 2.10000000e+01],
       [3.20000000e+01, 7.57920000e+00],
       [2.93072519e+01, 1.45000000e+01],
       [2.50000000e+01, 2.60000000e+01],
       [2.60000000e+01, 2.20250000e+01],
       [2.50000000e+01, 5.54417000e+01],
       [2.93072519e+01, 2.16792000e+01],
       [4.60000000e+01, 7.52417000e+01],
       [3.00000000e+01, 4.55000000e+01],
       [2.10000000e+01, 8.05000000e+00],
       [2.70000000e+01, 8.66250000e+00],
       [3.00000000e+01, 1.64866700e+02],
       [5.00000000e+00, 3.13875000e+01],
       [4.60000000e+01, 7.92000000e+01],
       [4.10000000e+01, 7.85000000e+00],
       [3.00000000e+01, 1.30000000e+01],
       [2.93072519e+01, 7.89580000e+00],
       [2.60000000e+01, 1.30000000e+01],
       [2.40000000e+01, 8.66250000e+00],
       [3.30000000e+01, 1.51550000e+02],
       [2.30000000e+01, 8.31583000e+01],
       [1.80000000e+01, 7.87920000e+00],
       [2.70000000e+01, 7.85420000e+00],
       [2.93072519e+01, 3.96000000e+01],
       [1.85000000e+01, 1.30000000e+01],
       [2.10000000e+01, 2.65500000e+01],
       [2.50000000e+01, 7.22920000e+00],
       [2.20000000e+01, 7.77500000e+00],
       [6.30000000e+01, 2.60000000e+01],
       [2.93072519e+01, 1.52458000e+01],
       [2.93072519e+01, 7.75000000e+00],
       [2.40000000e+01, 6.50000000e+01],
       [4.00000000e+01, 2.60000000e+01],
       [2.93072519e+01, 7.89580000e+00],
       [2.40000000e+01, 9.32500000e+00],
       [2.93072519e+01, 8.05000000e+00],
       [2.93072519e+01, 8.71250000e+00],
       [2.93072519e+01, 7.75000000e+00],
       [8.00000000e+00, 3.25000000e+01],
       [1.85000000e+01, 7.22920000e+00],
       [1.90000000e+01, 1.61000000e+01],
       [3.30000000e+01, 8.05000000e+00],
       [2.93072519e+01, 2.57417000e+01],
       [1.80000000e+01, 7.35000000e+01],
       [3.60000000e+01, 3.16792000e+01],
       [2.30000000e+01, 1.39000000e+01],
       [4.20000000e+01, 1.30000000e+01],
       [1.80000000e+01, 5.31000000e+01],
       [5.50000000e+01, 5.00000000e+01],
       [2.93072519e+01, 7.75000000e+00],
       [2.20000000e+01, 8.05000000e+00],
       [2.93072519e+01, 8.11250000e+00],
       [1.90000000e+01, 1.30000000e+01],
       [2.00000000e+01, 7.85420000e+00],
       [3.60000000e+01, 7.52417000e+01],
       [1.70000000e-01, 2.05750000e+01],
       [2.00000000e+01, 1.38625000e+01],
       [3.70000000e+01, 9.00000000e+01],
       [2.00000000e+01, 7.22500000e+00],
       [1.70000000e+01, 7.89580000e+00],
       [4.90000000e+01, 6.50000000e+01],
       [2.93072519e+01, 7.57500000e+00],
       [2.93072519e+01, 7.89580000e+00],
       [4.60000000e+01, 2.60000000e+01],
       [7.50000000e-01, 1.37750000e+01],
       [1.15000000e+01, 1.45000000e+01],
       [1.70000000e+01, 7.35000000e+01],
       [2.10000000e+01, 7.77500000e+00],
       [2.20000000e+01, 7.79580000e+00],
       [2.93072519e+01, 2.32500000e+01],
       [3.60000000e+01, 3.90000000e+01],
       [2.50000000e+01, 7.65000000e+00],
       [5.50000000e+01, 1.35633300e+02],
       [2.93072519e+01, 7.87920000e+00],
       [2.60000000e+01, 7.77500000e+00],
       [3.50000000e+01, 2.11500000e+02],
       [2.80000000e+01, 1.05000000e+01],
       [2.10000000e+01, 7.82080000e+00],
       [2.93072519e+01, 7.77500000e+00],
       [3.00000000e+01, 2.60000000e+01],
       [1.80000000e+01, 1.05000000e+01],
       [2.30000000e+01, 1.05000000e+01],
       [2.10000000e+01, 6.13792000e+01],
       [3.80000000e+01, 7.22920000e+00],
       [3.00000000e+01, 1.27375000e+01],
       [6.40000000e+01, 8.31583000e+01],
       [4.70000000e+01, 7.00000000e+00],
       [2.93072519e+01, 1.55000000e+01],
       [2.93072519e+01, 5.64958000e+01],
       [2.93072519e+01, 7.77920000e+00],
       [2.93072519e+01, 1.44583000e+01],
       [3.00000000e+00, 1.37750000e+01],
       [2.93072519e+01, 1.55792000e+01],
       [2.20000000e+01, 1.22875000e+01],
       [1.60000000e+01, 8.51670000e+00],
       [2.93072519e+01, 7.22500000e+00],
       [4.10000000e+01, 1.30000000e+01],
       [2.80000000e+01, 2.25250000e+01],
       [2.93072519e+01, 1.44542000e+01],
       [2.90000000e+01, 2.30000000e+01],
       [2.40000000e+01, 3.70042000e+01],
       [2.70000000e+01, 7.22500000e+00],
       [4.50000000e+01, 3.00000000e+01],
       [6.05000000e+01, 3.36627880e+01],
       [4.80000000e+01, 5.04958000e+01],
       [3.00000000e+01, 7.62920000e+00],
       [2.20000000e+01, 1.39000000e+01],
       [1.90000000e+01, 1.05000000e+01],
       [2.90000000e+01, 2.21779200e+02],
       [2.00000000e+01, 7.92500000e+00],
       [4.90000000e+01, 2.60000000e+01],
       [2.93072519e+01, 7.75000000e+00],
       [2.10000000e+01, 7.89580000e+00],
       [2.40000000e+01, 7.25000000e+00],
       [2.30000000e+01, 9.35000000e+01],
       [1.80000000e+01, 8.05000000e+00],
       [6.40000000e+01, 7.52500000e+01],
       [1.30000000e+01, 2.62375000e+02],
       [4.70000000e+01, 6.11750000e+01],
       [2.93072519e+01, 2.34500000e+01],
       [3.20000000e+01, 7.77500000e+00],
       [2.70000000e+01, 7.92500000e+00],
       [2.30000000e+01, 1.05000000e+01],
       [2.60000000e+01, 1.30000000e+01],
       [1.80000000e+01, 6.00000000e+01],
       [2.50000000e+01, 3.15000000e+01],
       [3.60000000e+01, 1.21833000e+01],
       [4.50000000e+01, 1.41083000e+01],
       [2.60000000e+01, 7.77500000e+00],
       [1.30000000e+01, 2.02500000e+01],
       [1.30000000e+01, 3.13875000e+01],
       [1.80000000e+01, 8.66250000e+00],
       [1.20000000e+01, 1.57500000e+01],
       [2.20000000e+01, 8.66250000e+00],
       [2.00000000e+01, 2.60000000e+01],
       [4.20000000e+01, 2.65500000e+01],
       [2.90000000e+01, 2.20250000e+01],
       [4.50000000e+01, 5.25542000e+01],
       [1.85000000e+01, 7.28330000e+00],
       [4.30000000e+01, 7.89580000e+00],
       [3.00000000e+01, 1.38583000e+01],
       [1.00000000e+01, 4.69000000e+01],
       [2.93072519e+01, 8.05000000e+00],
       [2.70000000e+01, 2.60000000e+01],
       [3.20000000e+01, 2.25250000e+01],
       [2.93072519e+01, 6.43750000e+00],
       [1.40000000e+01, 9.22500000e+00],
       [2.93072519e+01, 7.55000000e+00],
       [3.20000000e+01, 8.05000000e+00],
       [2.40000000e+01, 7.75000000e+00],
       [4.80000000e+01, 7.92000000e+01],
       [2.40000000e+01, 7.55000000e+00],
       [1.80000000e+01, 1.44542000e+01],
       [9.00000000e+00, 1.52458000e+01],
       [3.10000000e+01, 1.34500000e+02],
       [3.50000000e+01, 7.75000000e+00],
       [2.70000000e+01, 2.47520800e+02],
       [2.93072519e+01, 0.00000000e+00],
       [2.93072519e+01, 8.05000000e+00],
       [4.50000000e+01, 1.34500000e+02],
       [2.90000000e+01, 2.60000000e+01],
       [2.10000000e+01, 2.41500000e+01],
       [2.50000000e+01, 7.92500000e+00],
       [3.00000000e+01, 6.95000000e+00],
       [2.93072519e+01, 1.45000000e+01],
       [3.90000000e+01, 1.08900000e+02],
       [2.93072519e+01, 8.05000000e+00],
       [6.00000000e+01, 7.62917000e+01],
       [3.10000000e+01, 1.80000000e+01],
       [3.50000000e+01, 5.77500000e+01],
       [3.20000000e+01, 1.30000000e+01],
       [2.93072519e+01, 1.50458000e+01],
       [3.00000000e+01, 1.51550000e+02],
       [1.80000000e+01, 7.77500000e+00],
       [2.80000000e+01, 8.05000000e+00],
       [4.00000000e+01, 4.69000000e+01],
       [2.93072519e+01, 1.28750000e+01],
       [1.60000000e+01, 7.65000000e+00],
       [2.93072519e+01, 7.75000000e+00],
       [1.80000000e+01, 7.22920000e+00],
       [3.90000000e+01, 7.22920000e+00],
       [4.70000000e+01, 1.05000000e+01],
       [2.10000000e+01, 7.75000000e+00],
       [2.93072519e+01, 2.60000000e+01],
       [3.90000000e+01, 7.12833000e+01],
       [9.00000000e+00, 3.17080000e+00],
       [6.00000000e+00, 2.10750000e+01],
       [2.60000000e+01, 1.36779200e+02],
       [5.90000000e+01, 5.14792000e+01],
       [2.93072519e+01, 7.72080000e+00],
       [2.93072519e+01, 7.75000000e+00],
       [3.00000000e+01, 1.30000000e+01],
       [4.50000000e+01, 2.97000000e+01],
       [2.90000000e+01, 1.38583000e+01],
       [2.93072519e+01, 7.22500000e+00],
       [4.50000000e+01, 2.62375000e+02],
       [2.93072519e+01, 8.05000000e+00],
       [2.10000000e+01, 1.15000000e+01],
       [2.93072519e+01, 1.44542000e+01],
       [2.40000000e+01, 7.85420000e+00],
       [3.30000000e-01, 1.44000000e+01],
       [5.40000000e+01, 8.18583000e+01],
       [4.10000000e+01, 1.50458000e+01],
       [5.00000000e+01, 2.11500000e+02],
       [2.20000000e+01, 7.72500000e+00],
       [2.93072519e+01, 7.22920000e+00],
       [2.70000000e+01, 5.20000000e+01],
       [4.10000000e+01, 5.18625000e+01],
       [1.80000000e+01, 7.75000000e+00],
       [3.45000000e+01, 7.82920000e+00],
       [2.25000000e+01, 7.22500000e+00],
       [5.70000000e+01, 1.30000000e+01],
       [9.20000000e-01, 2.77500000e+01],
       [5.40000000e+01, 5.54417000e+01],
       [1.70000000e+01, 8.05000000e+00],
       [2.93072519e+01, 2.65500000e+01],
       [4.80000000e+01, 1.06425000e+02],
       [4.50000000e+01, 5.94000000e+01],
       [5.00000000e+01, 2.60000000e+01],
       [4.20000000e+01, 2.65500000e+01],
       [2.80000000e+01, 2.60000000e+01],
       [2.93072519e+01, 1.55000000e+01],
       [3.60000000e+01, 2.62375000e+02],
       [4.70000000e+01, 2.27525000e+02],
       [3.30000000e+01, 2.77208000e+01],
       [2.93072519e+01, 7.87920000e+00],
       [3.00000000e+01, 2.60000000e+01],
       [2.80000000e+01, 7.25000000e+00],
       [2.20000000e+01, 7.22500000e+00],
       [3.50000000e+01, 1.23500000e+01],
       [5.30000000e+01, 2.74458000e+01],
       [4.90000000e+01, 0.00000000e+00],
       [3.60000000e+01, 1.30000000e+01],
       [5.50000000e+01, 9.35000000e+01],
       [2.93072519e+01, 8.05000000e+00],
       [2.90000000e+01, 7.92500000e+00],
       [1.70000000e+01, 1.61000000e+01],
       [3.20000000e+01, 1.35000000e+01],
       [6.70000000e+01, 2.21779200e+02],
       [2.93072519e+01, 2.23583000e+01],
       [3.90000000e+01, 2.11337500e+02],
       [3.50000000e+01, 7.89580000e+00],
       [4.50000000e+01, 7.22500000e+00],
       [2.70000000e+01, 7.87920000e+00],
       [1.20000000e+01, 3.90000000e+01],
       [2.20000000e+01, 2.10000000e+01],
       [2.60000000e+01, 1.30000000e+01],
       [5.70000000e+01, 1.46520800e+02],
       [3.00000000e+01, 5.77500000e+01],
       [1.00000000e+00, 4.15792000e+01],
       [2.30000000e+01, 8.05000000e+00],
       [3.25000000e+01, 9.50000000e+00],
       [2.93072519e+01, 8.05000000e+00],
       [2.20000000e+01, 6.19792000e+01],
       [2.93072519e+01, 7.22920000e+00],
       [3.00000000e+01, 1.30000000e+01],
       [7.60000000e+01, 7.88500000e+01],
       [2.93072519e+01, 7.89580000e+00],
       [2.70000000e+01, 1.36779200e+02],
       [4.00000000e+01, 1.60000000e+01],
       [2.85000000e+01, 2.77208000e+01],
       [2.90000000e+01, 2.60000000e+01],
       [4.20000000e+01, 3.25000000e+01],
       [2.93072519e+01, 7.87920000e+00],
       [2.93072519e+01, 7.75000000e+00],
       [2.65000000e+01, 7.22500000e+00],
       [2.60000000e+01, 7.89580000e+00],
       [3.60000000e+01, 1.59000000e+01],
       [2.40000000e+01, 1.05000000e+01],
       [4.30000000e+01, 2.77208000e+01],
       [2.20000000e+01, 5.94000000e+01],
       [2.93072519e+01, 2.54667000e+01],
       [2.40000000e+01, 6.00000000e+01],
       [1.80000000e+01, 1.30000000e+01],
       [2.00000000e+01, 2.30000000e+01],
       [6.00000000e+00, 1.52458000e+01],
       [2.40000000e+01, 3.15000000e+01],
       [2.93072519e+01, 7.75000000e+00],
       [2.93072519e+01, 7.05000000e+00],
       [2.50000000e+01, 1.05000000e+01],
       [4.30000000e+01, 2.10000000e+01],
       [6.00000000e+00, 1.34500000e+02],
       [2.93072519e+01, 7.75000000e+00],
       [2.30000000e+01, 7.05000000e+00],
       [3.30000000e+01, 2.65500000e+01],
       [2.93072519e+01, 7.55000000e+00],
       [2.93072519e+01, 7.75000000e+00],
       [2.93072519e+01, 1.61000000e+01],
       [2.93072519e+01, 2.34500000e+01],
       [2.50000000e+01, 9.50000000e+00],
       [3.00000000e+01, 1.55500000e+01],
       [2.70000000e+01, 1.50333000e+01],
       [2.70000000e+01, 8.66250000e+00],
       [3.65000000e+01, 1.74000000e+01],
       [2.93072519e+01, 7.75000000e+00],
       [3.30000000e+01, 7.85420000e+00],
       [1.80000000e+01, 3.43750000e+01],
       [5.30000000e+01, 8.18583000e+01],
       [2.93072519e+01, 6.43750000e+00],
       [2.93072519e+01, 7.75000000e+00],
       [5.00000000e+01, 2.11500000e+02],
       [2.40000000e+01, 8.22667000e+01],
       [2.20000000e+01, 3.15000000e+01],
       [2.93072519e+01, 7.75000000e+00],
       [6.00000000e+01, 2.60000000e+01],
       [2.80000000e+01, 7.77500000e+00],
       [2.50000000e+01, 7.79580000e+00],
       [2.60000000e+01, 1.35000000e+01],
       [1.00000000e+00, 1.21833000e+01],
       [1.45000000e+01, 6.95500000e+01],
       [3.25000000e+01, 2.11500000e+02],
       [2.90000000e+01, 7.85420000e+00],
       [2.93072519e+01, 3.16833000e+01],
       [2.90000000e+01, 7.92500000e+00],
       [2.40000000e+01, 2.77208000e+01],
       [2.93072519e+01, 2.77208000e+01]])

In [59]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf, y_train)

y_pred = clf.predict(X_test_trf)

accuracy_score(y_test, y_pred)

0.6428571428571429

In [60]:
mi = MissingIndicator()

mi.fit(X_train)

MissingIndicator()

In [61]:
mi.features_

array([0, 1])

In [62]:
X_train_missing = mi.transform(X_train)

In [63]:
X_train_missing

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False]])

In [64]:
X_test_missing = mi.transform(X_test)

In [65]:
X_test_missing

array([[ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [66]:

X_train[['Age_NA' , 'Fare_NA']] = X_train_missing

In [67]:
X_train

      Age     Fare  Age_NA  Fare_NA
280  23.0   8.6625   False    False
284   2.0  20.2125   False    False
40   39.0  13.4167   False    False
17   21.0   7.2250   False    False
362  31.0  21.0000   False    False
..    ...      ...     ...      ...
299  29.0   7.8542   False    False
22    NaN  31.6833    True    False
72   29.0   7.9250   False    False
15   24.0  27.7208   False    False
168   NaN  27.7208    True    False

[334 rows x 4 columns]

In [68]:
X_test[['Age_NA', 'Fare_NA']] = X_test_missing

In [69]:
si = SimpleImputer()
x_train_trf2 = si.fit_transform(X_train)
x_test_trf2 = si.transform(X_test)

In [70]:
clf2 = LogisticRegression()
clf2.fit(x_train_trf2 , y_train)
y_pred2 = clf2.predict(x_test_trf2)
accuracy_score(y_test , y_pred2)

0.6428571428571429

### Using builtin indicator of scikit learn , no need to use above codes

In [71]:
si3 = SimpleImputer(add_indicator=True)
x_train_trf3 = si3.fit_transform(X_train)
x_test_trf3 = si3.transform(X_test)
clf = LogisticRegression()
clf.fit(x_train_trf3 , y_train)
y_pred = clf.predict(x_test_trf3)
accuracy_score(y_test , y_pred )

0.6428571428571429