In [12]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [13]:
df = pd.read_csv(r"C:\Users\Acer\OneDrive\Desktop\Machine Learning\CSV\Student_Performance.csv")

In [14]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [ ]:

def clean_data(df):
    
    df['Extracurricular Activities'] = df['Extracurricular Activities'].str.replace("^Yes$", "1", regex=True)
   
    df['Extracurricular Activities'] = df['Extracurricular Activities'].str.replace("^No$", "0", regex=True)
    return df

df_clean = clean_data(df.copy())
df= df_clean.copy()
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [ ]:
df['Extracurricular Activities'] = df['Extracurricular Activities'].astype(int)

In [23]:
x = df.iloc[: , 0:6]
y = df.iloc[: , -1]
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size= 0.2 , random_state=2)

In [25]:
x_train.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
8856,9,82,1,7,8,83.0
1545,7,76,0,8,8,71.0
8136,9,47,0,5,7,47.0
7768,3,60,1,9,1,40.0
7782,9,88,0,9,6,84.0

In [26]:
from sklearn.linear_model import LinearRegression
lr =LinearRegression()

In [27]:
lr.fit(x_train , y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)
y_pred

array([26., 34., 80., ..., 44., 31., 67.], shape=(2000,))

In [29]:
y_test

7878    26.0
3224    34.0
1919    80.0
4432    62.0
4835    83.0
        ...
9073    91.0
8584    15.0
5390    44.0
5092    31.0
2964    67.0
Name: Performance Index, Length: 2000, dtype: float64

In [30]:
from sklearn.metrics import accuracy_score , mean_absolute_error , mean_squared_error , r2_score

In [ ]:
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R^2 Score:", r2_score(y_test, y_pred))

Mean Absolute Error: 1.7038814803527203e-14
Mean Squared Error: 4.177144710890093e-28
Root Mean Squared Error: 2.0438064269617348e-14
R^2 Score: 1.0