In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import GridSearchCV

In [2]:
data = fetch_california_housing()
x, y = data.data, data.target

In [3]:
df = pd.DataFrame(data.data)

In [4]:
data.target_names

['MedHouseVal']

In [5]:
df.columns = data.feature_names
df['MedHouseVal'] = data.target

In [6]:
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [7]:
x= df.iloc[: , 0:8]
y= df.iloc[: , -1]

In [8]:
x

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train , x_test , y_train , y_test = train_test_split(x , y, test_size=0.2 , random_state=42)

In [11]:
x_train

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
14196,3.2596,33.0,5.017657,1.006421,2300.0,3.691814,32.71,-117.03
8267,3.8125,49.0,4.473545,1.041005,1314.0,1.738095,33.77,-118.16
17445,4.1563,4.0,5.645833,0.985119,915.0,2.723214,34.66,-120.48
14265,1.9425,36.0,4.002817,1.033803,1418.0,3.994366,32.69,-117.11
2271,3.5542,43.0,6.268421,1.134211,874.0,2.300000,36.78,-119.80
...,...,...,...,...,...,...,...,...
11284,6.3700,35.0,6.129032,0.926267,658.0,3.032258,33.78,-117.96
11964,3.0500,33.0,6.868597,1.269488,1753.0,3.904232,34.02,-117.43
5390,2.9344,36.0,3.986717,1.079696,1756.0,3.332068,34.03,-118.38
860,5.7192,15.0,6.395349,1.067979,1777.0,3.178891,37.58,-121.96
15795,2.5755,52.0,3.402576,1.058776,2619.0,2.108696,37.77,-122.42

In [12]:
from sklearn.tree import DecisionTreeRegressor

In [13]:
dtr = DecisionTreeRegressor(max_depth=9)

In [14]:
dtr.fit(x_train , y_train)

DecisionTreeRegressor(max_depth=9)

In [15]:
from sklearn.metrics import r2_score

In [16]:
y_pred = dtr.predict(x_test)

In [17]:
r2_score(y_test , y_pred)

0.6849075922716094

## Using dtreeviz to visualize tree .

## Hyperparameter tuning

In [18]:
param_dist = {
    'max_depth': [4, 8, None],
    'criterion': ['squared_error', 'absolute_error'],
    'max_features': [0.5, 1.0],
    'min_samples_split': [2, 5]
}

In [19]:
gd = GridSearchCV(DecisionTreeRegressor(),  param_grid=param_dist)

In [ ]:
gd.fit(x_train , y_train)

In [ ]:

gd.best_score_

np.float64(0.6970866548519401)

In [ ]:
gd.best_params_

{'criterion': 'squared_error',
 'max_depth': 8,
 'max_features': 1.0,
 'min_samples_split': 5}