In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\Acer\OneDrive\Desktop\Machine Learning\CSV\Student_Performance.csv")

In [3]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [4]:
from sklearn.preprocessing import LabelEncoder
lr = LabelEncoder()

In [7]:
df['Extracurricular Activities'] = lr.fit_transform(df['Extracurricular Activities'])

In [8]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  int64
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(5)
memory usage: 468.9 KB

In [11]:
x = df.iloc[: , :5]
y = df.iloc[: , -1]

In [13]:
x

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5
...,...,...,...,...,...
9995,1,49,1,4,2
9996,7,64,1,8,5
9997,6,83,1,8,5
9998,9,97,1,7,0
9999,7,74,0,8,1

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [15]:
clf1 = LinearRegression()
clf2 = DecisionTreeRegressor(max_depth=5)
clf3 = SVR()

In [16]:
estimators = [('lr' , clf1) , ('dtr' , clf2) , ('sv' , clf3)]

In [18]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import VotingRegressor

In [21]:
for estimator in estimators:
    out = cross_val_score(estimator[1] , x , y ,  cv=10 , scoring='r2')
    print(f"{estimator[0]}: {np.round(np.mean(out) ,2)}")

lr: 0.99
dtr: 0.96
sv: 0.99

In [ ]:
vr = VotingRegressor(estimators=estimators)
out = cross_val_score(vr , x , y , cv=10 ,scoring='r2')
print(f"{np.round(np.mean(out) , 2)}")

0.98